from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .schemas import MusicResult, to_plain_data


class KaggleAutoError(RuntimeError):
    pass


@dataclass(frozen=True)
class KaggleJobConfig:
    kaggle_backend: str = "musicgen"
    model: str = "facebook/musicgen-small"
    username: str | None = None
    machine_shape: str = "NvidiaTeslaP100"
    submit: bool = True
    wait: bool = False
    poll_seconds: int = 60
    timeout_seconds: int = 10_800


def run_or_stage_kaggle_job(
    result: MusicResult,
    output_root: str | Path,
    config: KaggleJobConfig | None = None,
) -> dict[str, Any]:
    config = config or KaggleJobConfig()
    state = stage_kaggle_job(result, output_root, config)
    if not config.submit:
        state["status"] = "staged"
        state["messages"].append("Job staged locally. Submit is disabled.")
        _write_state(state)
        return state

    readiness = kaggle_readiness(config.username)
    state["kaggle_ready"] = readiness["ready"]
    state["messages"].extend(readiness["messages"])
    _write_state(state)
    if not readiness["ready"]:
        state["status"] = "needs_setup"
        state["messages"].append("Install/configure Kaggle API, then rerun the generated commands.")
        _write_state(state)
        return state

    return submit_kaggle_job(
        state,
        wait=config.wait,
        poll_seconds=config.poll_seconds,
        timeout_seconds=config.timeout_seconds,
    )


def stage_kaggle_job(result: MusicResult, output_root: str | Path, config: KaggleJobConfig) -> dict[str, Any]:
    username = resolve_kaggle_username(config.username) or "YOUR_KAGGLE_USERNAME"
    run_dir = Path(output_root) / result.run_id
    job_dir = run_dir / "kaggle_job"
    dataset_dir = job_dir / "dataset"
    kernel_dir = job_dir / "kernel"
    download_dir = job_dir / "downloaded_output"
    dataset_dir.mkdir(parents=True, exist_ok=True)
    kernel_dir.mkdir(parents=True, exist_ok=True)
    download_dir.mkdir(parents=True, exist_ok=True)

    dataset_slug = slugify(f"genmusic-vn-job-{result.run_id}", max_length=48)
    kernel_slug = slugify(f"genmusic-vn-auto-{result.run_id}", max_length=48)
    dataset_ref = f"{username}/{dataset_slug}"
    kernel_ref = f"{username}/{kernel_slug}"

    (dataset_dir / "prompt_pack.json").write_text(
        json.dumps(_prompt_pack(result), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (dataset_dir / "train_config.json").write_text(
        json.dumps(
            {
                "backend": config.kaggle_backend,
                "model": config.model,
                "duration_seconds": result.duration_seconds,
                "created_at": _now(),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    (dataset_dir / "dataset-metadata.json").write_text(
        json.dumps(
            {
                "title": f"GenMusic VN Job {result.run_id[-8:]}",
                "id": dataset_ref,
                "licenses": [{"name": "other"}],
                "subtitle": "Prompt pack and control metadata for GenMusic VN.",
                "description": "Private automation dataset generated by the local GenMusic VN demo.",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    (kernel_dir / "run_genmusic_vn.py").write_text(_kernel_script(dataset_slug=dataset_slug), encoding="utf-8")
    (kernel_dir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": kernel_ref,
                "title": f"GenMusic VN Auto {result.run_id[-8:]}",
                "code_file": "run_genmusic_vn.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": "true",
                "enable_gpu": "true",
                "enable_internet": "true",
                "machine_shape": config.machine_shape,
                "dataset_sources": [dataset_ref],
                "competition_sources": [],
                "kernel_sources": [],
                "model_sources": [],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    commands = _commands(dataset_dir, kernel_dir, download_dir, kernel_ref)
    (job_dir / "run_commands.ps1").write_text("\n".join(commands) + "\n", encoding="utf-8")

    state = {
        "run_id": result.run_id,
        "status": "staged",
        "created_at": _now(),
        "kaggle_ready": False,
        "kaggle_backend": config.kaggle_backend,
        "model": config.model,
        "dataset_ref": dataset_ref,
        "kernel_ref": kernel_ref,
        "job_dir": str(job_dir),
        "dataset_dir": str(dataset_dir),
        "kernel_dir": str(kernel_dir),
        "download_dir": str(download_dir),
        "state_path": str(job_dir / "job_state.json"),
        "commands": commands,
        "messages": ["Kaggle job files prepared."],
        "history": [],
        "downloaded_files": [],
    }
    _write_state(state)
    return state


def submit_kaggle_job(
    state: dict[str, Any],
    *,
    wait: bool = False,
    poll_seconds: int = 60,
    timeout_seconds: int = 10_800,
) -> dict[str, Any]:
    cli = kaggle_cli_command()
    if cli is None:
        state["status"] = "needs_setup"
        state["messages"].append("Kaggle CLI was not found.")
        _write_state(state)
        return state

    dataset = _run(cli + ["datasets", "create", "-p", state["dataset_dir"], "-r", "zip"], timeout=600)
    state["history"].append(_history_item("datasets create", dataset))
    if dataset["returncode"] != 0:
        state["status"] = "failed"
        state["messages"].append("Dataset upload failed.")
        _write_state(state)
        return state

    state["status"] = "dataset_uploaded"
    state["messages"].append("Prompt pack dataset uploaded to Kaggle.")
    _write_state(state)

    pushed = _run(cli + ["kernels", "push", "-p", state["kernel_dir"]], timeout=600)
    state["history"].append(_history_item("kernels push", pushed))
    if pushed["returncode"] != 0:
        state["status"] = "failed"
        state["messages"].append("Kernel submit failed.")
        _write_state(state)
        return state

    state["status"] = "submitted"
    state["submitted_at"] = _now()
    state["messages"].append("Kaggle kernel submitted with GPU enabled.")
    _write_state(state)

    if wait:
        deadline = time.time() + timeout_seconds
        while time.time() < deadline:
            state = refresh_kaggle_job(state)
            if state["status"] in {"complete", "failed"}:
                return state
            time.sleep(max(5, poll_seconds))
        state["status"] = "timeout"
        state["messages"].append("Timed out while waiting for Kaggle job.")
        _write_state(state)
    return state


def refresh_kaggle_job(state_or_path: dict[str, Any] | str | Path) -> dict[str, Any]:
    state = _load_state(state_or_path)
    cli = kaggle_cli_command()
    if cli is None:
        state["status"] = "needs_setup"
        state["messages"].append("Kaggle CLI was not found.")
        _write_state(state)
        return state

    status = _run(cli + ["kernels", "status", state["kernel_ref"]], timeout=120)
    state["history"].append(_history_item("kernels status", status))
    text = f"{status['stdout']}\n{status['stderr']}".lower()
    state["last_status_output"] = status["stdout"] or status["stderr"]

    if status["returncode"] != 0:
        state["status"] = "failed"
        state["messages"].append("Could not read Kaggle kernel status.")
        _write_state(state)
        return state

    if any(marker in text for marker in ["complete", "completed", "succeeded"]):
        state["status"] = "complete"
        _download_kernel_output(state, cli)
    elif any(marker in text for marker in ["error", "failed", "cancelled", "canceled"]):
        state["status"] = "failed"
    elif "running" in text:
        state["status"] = "running"
    else:
        state["status"] = "submitted"

    state["checked_at"] = _now()
    _write_state(state)
    return state


def sync_kaggle_artifact(*, source: str, ref: str, output_dir: str | Path = "models/current") -> dict[str, Any]:
    cli = kaggle_cli_command()
    if cli is None:
        raise KaggleAutoError("Kaggle CLI was not found. Install with `pip install kaggle`.")

    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)
    if source == "dataset":
        command = cli + ["datasets", "download", ref, "-p", str(target), "--unzip"]
    elif source == "kernel":
        command = cli + ["kernels", "output", ref, "-p", str(target)]
    else:
        raise KaggleAutoError("Unsupported source. Use `dataset` or `kernel`.")

    result = _run(command, timeout=1800)
    manifest = {
        "source": source,
        "ref": ref,
        "output_dir": str(target),
        "synced_at": _now(),
        "command": command,
        "returncode": result["returncode"],
        "stdout": result["stdout"],
        "stderr": result["stderr"],
        "files": [str(path) for path in sorted(target.rglob("*")) if path.is_file()],
    }
    (target / "model_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    if result["returncode"] != 0:
        raise KaggleAutoError(result["stderr"] or result["stdout"] or "Kaggle sync failed.")
    return manifest


def kaggle_readiness(username: str | None = None) -> dict[str, Any]:
    messages: list[str] = []
    cli = kaggle_cli_command()
    if cli is None:
        messages.append("Kaggle CLI missing. Install with `pip install kaggle`.")

    user = resolve_kaggle_username(username)
    if not user:
        messages.append("Kaggle username missing. Put token at ~/.kaggle/kaggle.json or set KAGGLE_USERNAME.")

    has_key = bool(os.getenv("KAGGLE_KEY")) or (Path.home() / ".kaggle" / "kaggle.json").exists()
    if not has_key:
        messages.append("Kaggle API key missing. Download kaggle.json from Kaggle account settings.")

    return {"ready": cli is not None and bool(user) and has_key, "username": user, "messages": messages}


def resolve_kaggle_username(username: str | None = None) -> str | None:
    if username:
        return username.strip()
    env_user = os.getenv("KAGGLE_USERNAME")
    if env_user:
        return env_user.strip()
    token_path = Path.home() / ".kaggle" / "kaggle.json"
    if token_path.exists():
        try:
            data = json.loads(token_path.read_text(encoding="utf-8"))
            value = data.get("username")
            return value.strip() if isinstance(value, str) and value.strip() else None
        except json.JSONDecodeError:
            return None
    return None


def kaggle_cli_command() -> list[str] | None:
    executable = shutil.which("kaggle")
    if executable:
        return [executable]

    scripts_dir = Path(sys.executable).parent / "Scripts"
    candidate = scripts_dir / ("kaggle.exe" if os.name == "nt" else "kaggle")
    if candidate.exists():
        return [str(candidate)]
    return None


def slugify(value: str, max_length: int = 50) -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", normalized).strip("-").lower()
    slug = re.sub(r"-{2,}", "-", slug)
    if not slug:
        slug = "genmusic-vn"
    return slug[:max_length].strip("-")


def _prompt_pack(result: MusicResult) -> dict[str, Any]:
    return {
        "run_id": result.run_id,
        "duration_seconds": result.duration_seconds,
        "prompt": result.prompt,
        "negative_prompt": result.negative_prompt,
        "lyrics": to_plain_data(result.lyrics),
        "harmony": to_plain_data(result.harmony),
        "emotion": to_plain_data(result.emotion),
        "melody": to_plain_data(result.melody),
    }


def _kernel_script(dataset_slug: str) -> str:
    return f'''from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


DATASET_DIR = Path("/kaggle/input/{dataset_slug}")
PROMPT_PACK = DATASET_DIR / "prompt_pack.json"
TRAIN_CONFIG = DATASET_DIR / "train_config.json"
OUTPUT_DIR = Path("/kaggle/working/genmusic_vn")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def ensure(import_name: str, *pip_specs: str) -> None:
    try:
        __import__(import_name)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", *pip_specs])


def run_musicgen(prompt_pack: dict, config: dict) -> Path:
    ensure("audiocraft", "audiocraft")
    from audiocraft.data.audio import audio_write
    from audiocraft.models import MusicGen

    model_name = config.get("model") or "facebook/musicgen-small"
    model = MusicGen.get_pretrained(model_name)
    model.set_generation_params(duration=int(prompt_pack.get("duration_seconds", 30)))
    wav = model.generate([prompt_pack["prompt"]])
    stem = OUTPUT_DIR / f"{{prompt_pack.get('run_id', 'genmusic_vn')}}_musicgen"
    audio_write(str(stem), wav[0].cpu(), model.sample_rate, strategy="loudness", loudness_compressor=True)
    return stem.with_suffix(".wav")


def run_stable_audio_open(prompt_pack: dict, config: dict) -> Path:
    ensure("diffusers", "diffusers", "transformers", "accelerate", "soundfile")
    import soundfile as sf
    import torch
    from diffusers import StableAudioPipeline

    model_name = config.get("model") or "stabilityai/stable-audio-open-1.0"
    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.float16 if device == "cuda" else torch.float32
    pipe = StableAudioPipeline.from_pretrained(model_name, torch_dtype=dtype).to(device)
    generator = torch.Generator(device).manual_seed(42) if device == "cuda" else torch.Generator().manual_seed(42)
    audio = pipe(
        prompt_pack["prompt"],
        negative_prompt=prompt_pack.get("negative_prompt", "low quality"),
        num_inference_steps=100,
        audio_end_in_s=float(prompt_pack.get("duration_seconds", 30)),
        num_waveforms_per_prompt=1,
        generator=generator,
    ).audios
    output = audio[0].T.float().cpu().numpy()
    output_path = OUTPUT_DIR / f"{{prompt_pack.get('run_id', 'genmusic_vn')}}_stable_audio_open.wav"
    sf.write(output_path, output, pipe.vae.sampling_rate)
    return output_path


def main() -> None:
    prompt_pack = json.loads(PROMPT_PACK.read_text(encoding="utf-8"))
    config = json.loads(TRAIN_CONFIG.read_text(encoding="utf-8"))
    backend = config.get("backend", "musicgen")

    if backend == "musicgen":
        output_path = run_musicgen(prompt_pack, config)
    elif backend == "stable-audio-open":
        output_path = run_stable_audio_open(prompt_pack, config)
    else:
        raise SystemExit(f"Unsupported Kaggle backend: {{backend}}")

    result = {{
        "run_id": prompt_pack.get("run_id"),
        "backend": backend,
        "model": config.get("model"),
        "prompt": prompt_pack.get("prompt"),
        "negative_prompt": prompt_pack.get("negative_prompt"),
        "output_path": str(output_path),
    }}
    (OUTPUT_DIR / "kaggle_result.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUTPUT_DIR / "used_prompt_pack.json").write_text(json.dumps(prompt_pack, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False, indent=2))


main()
'''


def _commands(dataset_dir: Path, kernel_dir: Path, download_dir: Path, kernel_ref: str) -> list[str]:
    return [
        "pip install -U kaggle",
        "# Put kaggle.json in $HOME/.kaggle/kaggle.json, or set KAGGLE_USERNAME and KAGGLE_KEY.",
        f'kaggle datasets create -p "{dataset_dir}" -r zip',
        f'kaggle kernels push -p "{kernel_dir}"',
        f'kaggle kernels status "{kernel_ref}"',
        f'kaggle kernels output "{kernel_ref}" -p "{download_dir}"',
    ]


def _download_kernel_output(state: dict[str, Any], cli: list[str]) -> None:
    download_dir = Path(state["download_dir"])
    download_dir.mkdir(parents=True, exist_ok=True)
    if state.get("downloaded_files"):
        return
    output = _run(cli + ["kernels", "output", state["kernel_ref"], "-p", str(download_dir)], timeout=1800)
    state["history"].append(_history_item("kernels output", output))
    if output["returncode"] != 0:
        state["messages"].append("Kaggle job completed, but output download failed.")
        return
    state["downloaded_files"] = [str(path) for path in sorted(download_dir.rglob("*")) if path.is_file()]
    state["messages"].append("Kaggle output downloaded to local machine.")


def _load_state(state_or_path: dict[str, Any] | str | Path) -> dict[str, Any]:
    if isinstance(state_or_path, dict):
        return state_or_path
    return json.loads(Path(state_or_path).read_text(encoding="utf-8"))


def _write_state(state: dict[str, Any]) -> None:
    Path(state["state_path"]).write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


def _run(command: list[str], *, timeout: int) -> dict[str, Any]:
    env = os.environ.copy()
    env.setdefault("PYTHONIOENCODING", "utf-8")
    proc = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        env=env,
    )
    return {
        "command": command,
        "returncode": proc.returncode,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
    }


def _history_item(label: str, result: dict[str, Any]) -> dict[str, Any]:
    return {
        "label": label,
        "at": _now(),
        "command": result["command"],
        "returncode": result["returncode"],
        "stdout": result["stdout"][-4000:],
        "stderr": result["stderr"][-4000:],
    }


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()
