from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
import unicodedata
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from hashlib import sha1
from pathlib import Path
from typing import Any


class KaggleAutoError(RuntimeError):
    pass


@dataclass(frozen=True)
class KaggleJobConfig:
    model: str = "facebook/musicgen-small"
    username: str | None = None
    machine_shape: str = "NvidiaTeslaP100"
    submit: bool = True
    wait: bool = False
    poll_seconds: int = 60
    timeout_seconds: int = 10_800


def submit_text_to_music_job(
    *,
    text: str,
    output_root: str | Path = "outputs",
    duration_seconds: int = 30,
    genre: str | None = None,
    config: KaggleJobConfig | None = None,
) -> dict[str, Any]:
    config = config or KaggleJobConfig()
    state = stage_text_to_music_job(
        text=text,
        output_root=output_root,
        duration_seconds=duration_seconds,
        genre=genre,
        config=config,
    )
    if not config.submit:
        state["status"] = "staged"
        state["messages"].append("Job staged locally. Submit is disabled.")
        _write_state(state)
        return state

    readiness = kaggle_readiness(config.username)
    state["kaggle_ready"] = readiness["ready"]
    state["messages"].extend(readiness["messages"])
    _write_state(state)
    if not readiness["ready"]:
        state["status"] = "needs_setup"
        state["messages"].append("Install/configure Kaggle API, then rerun the generated commands.")
        _write_state(state)
        return state

    return submit_kaggle_job(
        state,
        wait=config.wait,
        poll_seconds=config.poll_seconds,
        timeout_seconds=config.timeout_seconds,
    )


def stage_text_to_music_job(
    *,
    text: str,
    output_root: str | Path,
    duration_seconds: int,
    genre: str | None,
    config: KaggleJobConfig,
) -> dict[str, Any]:
    normalized = " ".join(text.split()).strip()
    if not normalized:
        raise ValueError("Input text is empty.")

    duration_seconds = max(6, min(180, int(duration_seconds)))
    run_id = make_run_id(normalized)
    username = resolve_kaggle_username(config.username) or "YOUR_KAGGLE_USERNAME"
    run_dir = Path(output_root) / run_id
    job_dir = run_dir / "kaggle_job"
    dataset_dir = job_dir / "dataset"
    kernel_dir = job_dir / "kernel"
    download_dir = job_dir / "downloaded_output"
    dataset_dir.mkdir(parents=True, exist_ok=True)
    kernel_dir.mkdir(parents=True, exist_ok=True)
    download_dir.mkdir(parents=True, exist_ok=True)

    dataset_slug = slugify(f"genmusic-vn-job-{run_id}", max_length=48)
    kernel_slug = slugify(f"genmusic-vn-musicgen-{run_id}", max_length=48)
    dataset_ref = f"{username}/{dataset_slug}"
    kernel_ref = f"{username}/{kernel_slug}"

    request = {
        "run_id": run_id,
        "text": normalized,
        "duration_seconds": duration_seconds,
        "genre": genre or "Vietnamese cinematic background music",
        "model": config.model,
        "backend": "musicgen",
        "created_at": _now(),
    }
    (run_dir / "request.json").write_text(json.dumps(request, ensure_ascii=False, indent=2), encoding="utf-8")
    (dataset_dir / "request.json").write_text(json.dumps(request, ensure_ascii=False, indent=2), encoding="utf-8")
    _write_source_zip(dataset_dir / "genmusic_vn_source.zip")
    (dataset_dir / "dataset-metadata.json").write_text(
        json.dumps(
            {
                "title": f"GenMusic VN Request {run_id[-8:]}",
                "id": dataset_ref,
                "licenses": [{"name": "other"}],
                "subtitle": "Raw Vietnamese text request and pipeline source for Kaggle MusicGen generation.",
                "description": "Private automation dataset generated by the GenMusic VN local app.",
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    (kernel_dir / "run_genmusic_vn.py").write_text(_kernel_script(dataset_slug=dataset_slug), encoding="utf-8")
    (kernel_dir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": kernel_ref,
                "title": f"GenMusic VN MusicGen {run_id[-8:]}",
                "code_file": "run_genmusic_vn.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": "true",
                "enable_gpu": "true",
                "enable_internet": "true",
                "machine_shape": config.machine_shape,
                "dataset_sources": [dataset_ref],
                "competition_sources": [],
                "kernel_sources": [],
                "model_sources": [],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    commands = _commands(dataset_dir, kernel_dir, download_dir, kernel_ref)
    (job_dir / "run_commands.ps1").write_text("\n".join(commands) + "\n", encoding="utf-8")

    state = {
        "run_id": run_id,
        "status": "staged",
        "created_at": _now(),
        "kaggle_ready": False,
        "backend": "musicgen",
        "model": config.model,
        "dataset_ref": dataset_ref,
        "kernel_ref": kernel_ref,
        "run_dir": str(run_dir),
        "job_dir": str(job_dir),
        "dataset_dir": str(dataset_dir),
        "kernel_dir": str(kernel_dir),
        "download_dir": str(download_dir),
        "request_path": str(run_dir / "request.json"),
        "state_path": str(job_dir / "job_state.json"),
        "mp3_path": "",
        "mp3_url": "",
        "commands": commands,
        "messages": ["Kaggle MusicGen job files prepared."],
        "history": [],
        "downloaded_files": [],
    }
    _write_state(state)
    return state


def submit_kaggle_job(
    state: dict[str, Any],
    *,
    wait: bool = False,
    poll_seconds: int = 60,
    timeout_seconds: int = 10_800,
) -> dict[str, Any]:
    cli = kaggle_cli_command()
    if cli is None:
        state["status"] = "needs_setup"
        state["messages"].append("Kaggle CLI was not found.")
        _write_state(state)
        return state

    dataset = _run(cli + ["datasets", "create", "-p", state["dataset_dir"], "-r", "zip"], timeout=600)
    state["history"].append(_history_item("datasets create", dataset))
    if dataset["returncode"] != 0:
        state["status"] = "failed"
        state["messages"].append("Dataset upload failed.")
        _write_state(state)
        return state

    state["status"] = "dataset_uploaded"
    state["messages"].append("Raw text request and source uploaded to Kaggle.")
    _write_state(state)

    pushed = _run(cli + ["kernels", "push", "-p", state["kernel_dir"]], timeout=600)
    state["history"].append(_history_item("kernels push", pushed))
    if pushed["returncode"] != 0:
        state["status"] = "failed"
        state["messages"].append("Kernel submit failed.")
        _write_state(state)
        return state

    state["status"] = "submitted"
    state["submitted_at"] = _now()
    state["messages"].append("Kaggle MusicGen kernel submitted with GPU enabled.")
    _write_state(state)

    if wait:
        deadline = time.time() + timeout_seconds
        while time.time() < deadline:
            state = refresh_kaggle_job(state)
            if state["status"] in {"complete", "failed"}:
                return state
            time.sleep(max(5, poll_seconds))
        state["status"] = "timeout"
        state["messages"].append("Timed out while waiting for Kaggle job.")
        _write_state(state)
    return state


def refresh_kaggle_job(state_or_path: dict[str, Any] | str | Path) -> dict[str, Any]:
    state = _load_state(state_or_path)
    cli = kaggle_cli_command()
    if cli is None:
        state["status"] = "needs_setup"
        state["messages"].append("Kaggle CLI was not found.")
        _write_state(state)
        return state

    status = _run(cli + ["kernels", "status", state["kernel_ref"]], timeout=120)
    state["history"].append(_history_item("kernels status", status))
    text = f"{status['stdout']}\n{status['stderr']}".lower()
    state["last_status_output"] = status["stdout"] or status["stderr"]

    if status["returncode"] != 0:
        state["status"] = "failed"
        state["messages"].append("Could not read Kaggle kernel status.")
        _write_state(state)
        return state

    if any(marker in text for marker in ["complete", "completed", "succeeded"]):
        state["status"] = "complete"
        _download_kernel_output(state, cli)
    elif any(marker in text for marker in ["error", "failed", "cancelled", "canceled"]):
        state["status"] = "failed"
    elif "running" in text:
        state["status"] = "running"
    else:
        state["status"] = "submitted"

    state["checked_at"] = _now()
    _write_state(state)
    return state


def sync_kaggle_artifact(*, source: str, ref: str, output_dir: str | Path = "models/current") -> dict[str, Any]:
    cli = kaggle_cli_command()
    if cli is None:
        raise KaggleAutoError("Kaggle CLI was not found. Install with `pip install kaggle`.")

    target = Path(output_dir)
    target.mkdir(parents=True, exist_ok=True)
    if source == "dataset":
        command = cli + ["datasets", "download", ref, "-p", str(target), "--unzip"]
    elif source == "kernel":
        command = cli + ["kernels", "output", ref, "-p", str(target)]
    else:
        raise KaggleAutoError("Unsupported source. Use `dataset` or `kernel`.")

    result = _run(command, timeout=1800)
    manifest = {
        "source": source,
        "ref": ref,
        "output_dir": str(target),
        "synced_at": _now(),
        "command": command,
        "returncode": result["returncode"],
        "stdout": result["stdout"],
        "stderr": result["stderr"],
        "files": [str(path) for path in sorted(target.rglob("*")) if path.is_file()],
    }
    (target / "model_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    if result["returncode"] != 0:
        raise KaggleAutoError(result["stderr"] or result["stdout"] or "Kaggle sync failed.")
    return manifest


def kaggle_readiness(username: str | None = None) -> dict[str, Any]:
    messages: list[str] = []
    cli = kaggle_cli_command()
    if cli is None:
        messages.append("Kaggle CLI missing. Install with `pip install kaggle`.")

    user = resolve_kaggle_username(username)
    if not user:
        messages.append("Kaggle username missing. Put token at ~/.kaggle/kaggle.json or set KAGGLE_USERNAME.")

    has_key = bool(os.getenv("KAGGLE_KEY")) or (Path.home() / ".kaggle" / "kaggle.json").exists()
    if not has_key:
        messages.append("Kaggle API key missing. Download kaggle.json from Kaggle account settings.")

    return {"ready": cli is not None and bool(user) and has_key, "username": user, "messages": messages}


def resolve_kaggle_username(username: str | None = None) -> str | None:
    if username:
        return username.strip()
    env_user = os.getenv("KAGGLE_USERNAME")
    if env_user:
        return env_user.strip()
    token_path = Path.home() / ".kaggle" / "kaggle.json"
    if token_path.exists():
        try:
            data = json.loads(token_path.read_text(encoding="utf-8"))
            value = data.get("username")
            return value.strip() if isinstance(value, str) and value.strip() else None
        except json.JSONDecodeError:
            return None
    return None


def kaggle_cli_command() -> list[str] | None:
    executable = shutil.which("kaggle")
    if executable:
        return [executable]

    scripts_dir = Path(sys.executable).parent / "Scripts"
    candidate = scripts_dir / ("kaggle.exe" if os.name == "nt" else "kaggle")
    if candidate.exists():
        return [str(candidate)]
    return None


def make_run_id(text: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    digest = sha1(text.encode("utf-8")).hexdigest()[:8]
    return f"{timestamp}-{digest}"


def slugify(value: str, max_length: int = 50) -> str:
    normalized = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", normalized).strip("-").lower()
    slug = re.sub(r"-{2,}", "-", slug)
    if not slug:
        slug = "genmusic-vn"
    return slug[:max_length].strip("-")


def _kernel_script(dataset_slug: str) -> str:
    return f'''from __future__ import annotations

import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path


DATASET_DIR = Path("/kaggle/input/{dataset_slug}")
REQUEST_PATH = DATASET_DIR / "request.json"
SOURCE_ZIP = DATASET_DIR / "genmusic_vn_source.zip"
SOURCE_DIR = Path("/kaggle/working/genmusic_vn_source")
PIPELINE_DIR = Path("/kaggle/working/pipeline_output")
OUTPUT_DIR = Path("/kaggle/working/genmusic_vn")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def ensure(import_name: str, *pip_specs: str) -> None:
    try:
        __import__(import_name)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", *pip_specs])


def prepare_source() -> None:
    if SOURCE_DIR.exists():
        shutil.rmtree(SOURCE_DIR)
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(SOURCE_ZIP) as archive:
        archive.extractall(SOURCE_DIR)
    sys.path.insert(0, str(SOURCE_DIR))


def render_musicgen_mp3(request: dict, prompt: str, negative_prompt: str) -> Path:
    ensure("audiocraft", "audiocraft")
    from audiocraft.data.audio import audio_write
    from audiocraft.models import MusicGen

    model_name = request.get("model") or "facebook/musicgen-small"
    duration = int(request.get("duration_seconds", 30))
    model = MusicGen.get_pretrained(model_name)
    model.set_generation_params(duration=duration)
    wav = model.generate([prompt])
    stem = OUTPUT_DIR / f"{{request.get('run_id', 'genmusic_vn')}}_musicgen"
    audio_write(str(stem), wav[0].cpu(), model.sample_rate, strategy="loudness", loudness_compressor=True)
    wav_path = stem.with_suffix(".wav")
    mp3_path = OUTPUT_DIR / f"{{request.get('run_id', 'genmusic_vn')}}.mp3"
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(wav_path), "-codec:a", "libmp3lame", "-qscale:a", "2", str(mp3_path)],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return mp3_path


def main() -> None:
    request = json.loads(REQUEST_PATH.read_text(encoding="utf-8"))
    prepare_source()

    from genmusic_vn.pipeline import create_music_project
    from genmusic_vn.schemas import to_plain_data

    result = create_music_project(
        text=request["text"],
        output_root=PIPELINE_DIR,
        backend="guide",
        duration_seconds=int(request.get("duration_seconds", 30)),
        genre=request.get("genre"),
        render_audio=False,
    )
    mp3_path = render_musicgen_mp3(request, result.prompt, result.negative_prompt)

    report = to_plain_data(result)
    final = {{
        "run_id": request.get("run_id"),
        "backend": "musicgen",
        "model": request.get("model"),
        "mp3_path": str(mp3_path),
        "prompt": result.prompt,
        "negative_prompt": result.negative_prompt,
        "analysis": report,
    }}
    (OUTPUT_DIR / "kaggle_result.json").write_text(json.dumps(final, ensure_ascii=False, indent=2), encoding="utf-8")
    (OUTPUT_DIR / "request.json").write_text(json.dumps(request, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({{"mp3_path": str(mp3_path), "prompt": result.prompt}}, ensure_ascii=False, indent=2))


main()
'''


def _write_source_zip(path: Path) -> None:
    root = Path(__file__).resolve().parents[1]
    include_roots = [root / "genmusic_vn"]
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for include_root in include_roots:
            for file_path in include_root.rglob("*"):
                if not file_path.is_file():
                    continue
                if "__pycache__" in file_path.parts or file_path.suffix in {".pyc", ".pyo"}:
                    continue
                archive.write(file_path, file_path.relative_to(root))
        archive.write(root / "pyproject.toml", "pyproject.toml")


def _commands(dataset_dir: Path, kernel_dir: Path, download_dir: Path, kernel_ref: str) -> list[str]:
    return [
        "pip install -U kaggle",
        "# Put kaggle.json in $HOME/.kaggle/kaggle.json, or set KAGGLE_USERNAME and KAGGLE_KEY.",
        f'kaggle datasets create -p "{dataset_dir}" -r zip',
        f'kaggle kernels push -p "{kernel_dir}"',
        f'kaggle kernels status "{kernel_ref}"',
        f'kaggle kernels output "{kernel_ref}" -p "{download_dir}"',
    ]


def _download_kernel_output(state: dict[str, Any], cli: list[str]) -> None:
    download_dir = Path(state["download_dir"])
    download_dir.mkdir(parents=True, exist_ok=True)
    output = _run(cli + ["kernels", "output", state["kernel_ref"], "-p", str(download_dir)], timeout=1800)
    state["history"].append(_history_item("kernels output", output))
    if output["returncode"] != 0:
        state["messages"].append("Kaggle job completed, but output download failed.")
        return
    files = [path for path in sorted(download_dir.rglob("*")) if path.is_file()]
    mp3_files = [path for path in files if path.suffix.lower() == ".mp3"]
    state["downloaded_files"] = [str(path) for path in files]
    if mp3_files:
        mp3_path = mp3_files[0]
        state["mp3_path"] = str(mp3_path)
        try:
            relative = mp3_path.relative_to(Path(state["run_dir"]))
            state["mp3_url"] = "/outputs/" + f"{state['run_id']}/{relative.as_posix()}"
        except ValueError:
            state["mp3_url"] = ""
        state["messages"].append("Kaggle output MP3 downloaded to local machine.")
    else:
        state["messages"].append("Kaggle output downloaded, but no MP3 file was found.")


def _load_state(state_or_path: dict[str, Any] | str | Path) -> dict[str, Any]:
    if isinstance(state_or_path, dict):
        return state_or_path
    return json.loads(Path(state_or_path).read_text(encoding="utf-8"))


def _write_state(state: dict[str, Any]) -> None:
    Path(state["state_path"]).write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")


def _run(command: list[str], *, timeout: int) -> dict[str, Any]:
    env = os.environ.copy()
    env.setdefault("PYTHONIOENCODING", "utf-8")
    proc = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        env=env,
    )
    return {
        "command": command,
        "returncode": proc.returncode,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
    }


def _history_item(label: str, result: dict[str, Any]) -> dict[str, Any]:
    return {
        "label": label,
        "at": _now(),
        "command": result["command"],
        "returncode": result["returncode"],
        "stdout": result["stdout"][-4000:],
        "stderr": result["stderr"][-4000:],
    }


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()

