"""Stage a reproducible JAM/DiffRhythm SFT kernel for Kaggle."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .kaggle_auto import KaggleJobConfig, _commands, _now, _write_source_zip, _write_state, make_run_id, resolve_kaggle_username, slugify


JAM_MODEL_ID = "genmusic-vn/jam-diffrhythm-cfm-dit"


def stage_jam_sft_kernel(
    *,
    preprocessed_dataset_ref: str,
    output_root: str | Path = "outputs/jam_kaggle",
    preset: str = "diffrhythm",
    steps: int = 100_000,
    batch_size: int = 2,
    username: str | None = None,
    machine_shape: str = "NvidiaTeslaT4",
    seed: int = 5602,
) -> dict[str, Any]:
    """Create local Kaggle dataset/kernel metadata without submitting it."""

    if "/" not in preprocessed_dataset_ref:
        raise ValueError("preprocessed_dataset_ref phải có dạng username/dataset-slug.")
    run_id = make_run_id(f"jam-sft-{preset}-{steps}-{seed}")
    user = resolve_kaggle_username(username) or "YOUR_KAGGLE_USERNAME"
    dataset_slug = slugify(preprocessed_dataset_ref.split("/", 1)[1])
    run_dir = Path(output_root) / run_id
    job_dir = run_dir / "jam_sft"
    dataset_dir = job_dir / "dataset"
    kernel_dir = job_dir / "kernel"
    download_dir = job_dir / "downloaded_output"
    for path in (dataset_dir, kernel_dir, download_dir):
        path.mkdir(parents=True, exist_ok=True)
    private_ref = f"{user}/{slugify(f'genmusic-vn-jam-source-{run_id}', max_length=48)}"
    kernel_ref = f"{user}/{slugify(f'genmusic-vn-jam-sft-{run_id}', max_length=48)}"
    request = {
        "run_id": run_id,
        "job_kind": "jam_sft",
        "model": JAM_MODEL_ID,
        "preset": preset,
        "steps": int(steps),
        "batch_size": int(batch_size),
        "seed": int(seed),
        "preprocessed_dataset_ref": preprocessed_dataset_ref,
        "created_at": _now(),
    }
    (run_dir / "training_request.json").write_text(json.dumps(request, ensure_ascii=False, indent=2), encoding="utf-8")
    (dataset_dir / "training_request.json").write_text(json.dumps(request, ensure_ascii=False, indent=2), encoding="utf-8")
    _write_source_zip(dataset_dir / "genmusic_vn_source.zip")
    script_name = "run_train_jam_sft.py"
    source_slug = private_ref.split("/", 1)[1]
    (kernel_dir / script_name).write_text(_jam_kernel_script(dataset_slug, source_slug, preset, steps, batch_size, seed), encoding="utf-8")
    (kernel_dir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": kernel_ref,
                "title": kernel_ref.rsplit("/", 1)[-1],
                "code_file": script_name,
                "language": "python",
                "kernel_type": "script",
                "is_private": "true",
                "enable_gpu": "true",
                "enable_internet": "true",
                "machine_shape": machine_shape,
                "dataset_sources": [private_ref, preprocessed_dataset_ref],
                "competition_sources": [],
                "kernel_sources": [],
                "model_sources": [],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    commands = _commands(dataset_dir, kernel_dir, download_dir, kernel_ref)
    (job_dir / "run_commands.ps1").write_text("\n".join(commands) + "\n", encoding="utf-8")
    state = {
        "run_id": run_id,
        "job_kind": "jam_sft",
        "status": "staged",
        "created_at": _now(),
        "kaggle_ready": False,
        "backend": "conditional-flow-matching-dit",
        "model": JAM_MODEL_ID,
        "preset": preset,
        "dataset_ref": private_ref,
        "preprocessed_dataset_ref": preprocessed_dataset_ref,
        "kernel_ref": kernel_ref,
        "run_dir": str(run_dir),
        "job_dir": str(job_dir),
        "dataset_dir": str(dataset_dir),
        "kernel_dir": str(kernel_dir),
        "download_dir": str(download_dir),
        "state_path": str(job_dir / "job_state.json"),
        "commands": commands,
        "messages": ["Đã stage kernel Kaggle cho SFT CFM-DiT; chưa submit."],
        "history": [],
    }
    _write_state(state)
    return state


def _jam_kernel_script(dataset_slug: str, source_slug: str, preset: str, steps: int, batch_size: int, seed: int) -> str:
    return f'''"""Kaggle entrypoint generated by GenMusic VN."""
import json
import shutil
import sys
import zipfile
from pathlib import Path

source_zip = Path("/kaggle/input") / "{source_slug}" / "genmusic_vn_source.zip"
if source_zip.exists():
    with zipfile.ZipFile(source_zip) as archive:
        archive.extractall("/kaggle/working/genmusic_vn_source")
    sys.path.insert(0, "/kaggle/working/genmusic_vn_source")

manifest = Path("/kaggle/input/{dataset_slug}") / "manifest.jsonl"
output = Path("/kaggle/working/jam_sft")
if not manifest.exists():
    raise FileNotFoundError(f"Không tìm thấy manifest đã tiền xử lý: {{manifest}}")
from genmusic_vn.training.sft import SFTConfig, train_sft_from_manifest

report = train_sft_from_manifest(
    manifest,
    output,
    config=SFTConfig(preset="{preset}", steps={int(steps)}, batch_size={int(batch_size)}, seed={int(seed)}, device="cuda"),
)
(output / "kaggle_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, indent=2))
'''
